"""
Persistent user preferences for MORPHEUS.

Stores defaults in ~/.morpheus/config.toml so users don't have to
re-specify cipher, KDF, chaining, padding, etc. every session.

CLI arguments always override saved preferences.
"""

from __future__ import annotations

import os
from pathlib import Path

_CONFIG_DIR = Path.home() / ".morpheus"
_CONFIG_FILE = _CONFIG_DIR / "config.toml"

# Keys that map to boolean CLI flags
_BOOL_KEYS = frozenset({"chain", "pad", "fixed_size", "no_filename", "check_leaks", "passphrase"})

# Keys that map to string CLI arguments
_STRING_KEYS = frozenset({"cipher", "kdf"})

_ALL_KEYS = _BOOL_KEYS | _STRING_KEYS

# Valid values for string keys (validated on load)
_VALID_VALUES = {
    "cipher": {"AES-256-GCM", "ChaCha20-Poly1305"},
    "kdf": {"Argon2id", "Scrypt"},
}


def config_path() -> Path:
    """Return the config file path."""
    return _CONFIG_FILE


def load_config() -> dict[str, str | bool]:
    """Load saved preferences from ~/.morpheus/config.toml.

    Returns an empty dict if the file doesn't exist or can't be parsed.
    Invalid keys and values are silently skipped.
    """
    if not _CONFIG_FILE.is_file():
        return {}

    result: dict[str, str | bool] = {}
    try:
        text = _CONFIG_FILE.read_text(encoding="utf-8")
    except OSError:
        return {}

    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, raw_value = line.partition("=")
        key = key.strip()
        raw_value = raw_value.strip()

        if key not in _ALL_KEYS:
            continue

        if key in _BOOL_KEYS:
            if raw_value.lower() in ("true", "1", "yes"):
                result[key] = True
            elif raw_value.lower() in ("false", "0", "no"):
                result[key] = False
        elif key in _STRING_KEYS:
            # Strip quotes
            val = raw_value.strip("\"'")
            if key in _VALID_VALUES and val not in _VALID_VALUES[key]:
                continue
            result[key] = val

    return result


def save_config(settings: dict[str, str | bool]) -> Path:
    """Save preferences to ~/.morpheus/config.toml.

    Only known keys are written. Returns the path written to.
    Validates string values before saving.
    """
    # Restrict directory permissions (0o700) before writing the file
    old_umask = os.umask(0o077)
    try:
        _CONFIG_DIR.mkdir(parents=True, exist_ok=True)

        lines = [
            "# MORPHEUS user preferences",
            "# Generated by: morpheus --save-config",
            "# CLI arguments always override these defaults.",
            "",
        ]

        for key in sorted(_ALL_KEYS):
            if key not in settings:
                continue
            val = settings[key]
            if isinstance(val, bool):
                lines.append(f"{key} = {'true' if val else 'false'}")
            elif key in _VALID_VALUES and val not in _VALID_VALUES[key]:
                continue  # reject invalid values on save too
            else:
                lines.append(f'{key} = "{val}"')

        lines.append("")  # trailing newline

        # Write atomically with restricted permissions from the start
        fd = os.open(str(_CONFIG_FILE), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w") as fh:
            fh.write("\n".join(lines))
    finally:
        os.umask(old_umask)

    return _CONFIG_FILE


def apply_config_defaults(args, config: dict[str, str | bool], raw_argv: list[str] | None = None) -> None:
    """Apply saved config as defaults for unset CLI arguments.

    Only fills in values that were not explicitly provided on the command line.
    Uses *raw_argv* (the original sys.argv) to detect which flags the user
    actually specified.  This avoids the bug where an explicit ``--cipher
    AES-256-GCM`` (which happens to equal the argparse default) was silently
    overridden by the saved config.

    Modifies args namespace in place.
    """
    raw_argv = raw_argv or []
    raw_text = " ".join(raw_argv)

    for key, value in config.items():
        if key in _BOOL_KEYS:
            # Boolean flags default to False; only apply if user didn't set them
            flag = f"--{key.replace('_', '-')}"
            if flag not in raw_text and not getattr(args, key, False):
                setattr(args, key, value)
        elif key in _STRING_KEYS:
            # Only apply if the flag wasn't explicitly passed on the command line
            flag = f"--{key.replace('_', '-')}"
            if flag not in raw_text:
                setattr(args, key, value)
