"""
Persistent user preferences for MORPHEUS.

Stores defaults in ~/.morpheus/config.toml so users don't have to
re-specify cipher, KDF, chaining, padding, etc. every session.

CLI arguments always override saved preferences.
"""

from __future__ import annotations

import os
from pathlib import Path

_CONFIG_DIR = Path.home() / ".morpheus"
_CONFIG_FILE = _CONFIG_DIR / "config.toml"

# Keys that map to boolean CLI flags.
#
# `passphrase` and `check_leaks` are deliberately absent. Both change
# security behaviour rather than output format, and a config file is a soft
# target: `passphrase` swaps the 12-char/4-class policy for a weaker
# word-based one, and `check_leaks` sends a hash of every password to a third
# party over the network. Neither should be reachable by editing a file that
# nothing prompts about. They remain available as explicit CLI flags.
_BOOL_KEYS = frozenset({"chain", "pad", "fixed_size", "no_filename"})

# Keys that map to string CLI arguments
_STRING_KEYS = frozenset({"cipher", "kdf"})

_ALL_KEYS = _BOOL_KEYS | _STRING_KEYS

# Valid values for string keys (validated on load)
_VALID_VALUES = {
    "cipher": {"AES-256-GCM", "ChaCha20-Poly1305"},
    "kdf": {"Argon2id", "Scrypt"},
}


def config_path() -> Path:
    """Return the config file path."""
    return _CONFIG_FILE


def load_config() -> dict[str, str | bool]:
    """Load saved preferences from ~/.morpheus/config.toml.

    Returns an empty dict if the file doesn't exist or can't be parsed.
    Invalid keys and values are silently skipped.
    """
    if not _CONFIG_FILE.is_file():
        return {}

    result: dict[str, str | bool] = {}
    try:
        text = _CONFIG_FILE.read_text(encoding="utf-8")
    except OSError:
        return {}

    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, raw_value = line.partition("=")
        key = key.strip()
        raw_value = raw_value.strip()

        if key not in _ALL_KEYS:
            continue

        if key in _BOOL_KEYS:
            if raw_value.lower() in ("true", "1", "yes"):
                result[key] = True
            elif raw_value.lower() in ("false", "0", "no"):
                result[key] = False
        elif key in _STRING_KEYS:
            # Strip quotes
            val = raw_value.strip("\"'")
            if key in _VALID_VALUES and val not in _VALID_VALUES[key]:
                continue
            result[key] = val

    return result


def save_config(settings: dict[str, str | bool]) -> Path:
    """Save preferences to ~/.morpheus/config.toml.

    Only known keys are written. Returns the path written to.
    """
    _CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# MORPHEUS user preferences",
        "# Generated by: morpheus --save-config",
        "# CLI arguments always override these defaults.",
        "",
    ]

    for key in sorted(_ALL_KEYS):
        if key not in settings:
            continue
        val = settings[key]
        if isinstance(val, bool):
            lines.append(f"{key} = {'true' if val else 'false'}")
        else:
            lines.append(f'{key} = "{val}"')

    lines.append("")  # trailing newline
    _CONFIG_FILE.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(_CONFIG_FILE, 0o600)  # user-only read/write
    return _CONFIG_FILE
